### ISSUE TITLE
conflict with Mystical world Mystical library

### ISSUE THREAD

**Issue by ferreiraalex** [Rebirth-of-the-Night/BetterWithMods#2]
[crash-2023-08-10_06.43.47-client.txt](https://github.com/Rebirth-of-the-Night/BetterWithMods/files/12308705/crash-2023-08-10_06.43.47-client.txt)

**Comment by democat3457** [comment]
What does this have to do with BetterWithMods? The crash is caused by Roots and Mystical Lib.

**Comment by ferreiraalex** [comment]
I delete your better with everything and restore better with mods and all work again
In crash writes roots:husk can't be crafted but I cant find what is it I think conflict in registry anything

**Comment by ferreiraalex** [comment]
I can send you latest log and debug but I say I restore better with mods old and all good and only with your mod I have this issue but I wanna use it, thanks so much

**Comment by ferreiraalex** [comment]
Write me on discord we can talk about it maybe we can solve this

sashawai

**Comment by aking4125** [comment]
Can confirm. Adding this mod causes the above crash. Disabling this mod and the game loads normally.

**Comment by democat3457** [comment]
> Can confirm. Adding this mod causes the above crash. Disabling this mod and the game loads normally.

@aking4125 hmm can i get a debug.log?

**Comment by DeusExNihil** [comment]
Not the same person, but having the same incompatibility. 
[latest.log](https://github.com/Rebirth-of-the-Night/BetterWithMods/files/13461388/latest.log)
[debug.log](https://github.com/Rebirth-of-the-Night/BetterWithMods/files/13461389/debug.log)

**Comment by democat3457** [comment]
> Not the same person, but having the same incompatibility. 
> 
> [latest.log](https://github.com/Rebirth-of-the-Night/BetterWithMods/files/13461388/latest.log)
> 
> [debug.log](https://github.com/Rebirth-of-the-Night/BetterWithMods/files/13461389/debug.log)

interesting... the error in the log doesn't seem related at all:

```
[17:15:59] [Client thread/ERROR] [FML]: Exception caught during firing event epicsquid.mysticallib.event.RegisterModRecipesEvent@2390d697:
java.lang.IllegalArgumentException: Invalid ingredient for recipe roots:husk
	at epicsquid.roots.init.ModRecipes.addSummonCreatureEntry(ModRecipes.java:209) ~[ModRecipes.class:?]
	at epicsquid.roots.init.ModRecipes.addSummonCreatureEntry(ModRecipes.java:188) ~[ModRecipes.class:?]
	at epicsquid.roots.init.ModRecipes.initSummonCreatureEntries(ModRecipes.java:178) ~[ModRecipes.class:?]
	at epicsquid.roots.init.ModRecipes.initRecipes(ModRecipes.java:1180) ~[ModRecipes.class:?]
	at epicsquid.roots.RegistryManager.initRecipes(RegistryManager.java:45) ~[RegistryManager.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3875_RegistryManager_initRecipes_RegisterModRecipesEvent.invoke(.dynamic) ~[?:?]
```

(same error as above)

I'll look into it some more.
